id: QmXSZPcaHn9V6rrYm3GFL4PycwPP4QxZR18P8fbFRXHgiW
description: ""
tags: []
trigger:
    type: https
    method: POST
    paths:
        - /ping
domains:
    - generated
includes:
    - /backend/functions/shorten.go
execution:
    timeout: 10s
    memory: 10MB
    call: shorten
