id: QmXSZPcaHn9V6rrYm3GFL4PycwPP4QxZR18P8fbFRXHgiW
description: ""
tags: []
source: .
trigger:
    type: https
    method: POST
    paths:
        - /ping
domains:
    - generated
execution:
    timeout: 10s
    memory: 10MB
    call: shorten
